OLD_TO_NEW_MAPPING = {
    "name": "user_name",
    "n_users": "num_users",
    "us_pref": "user_preference",
    "P": "power",
    "P_11": "p_11",
    "P_12": "p_12",
    "P_21": "p_21",
    "P_22": "p_22",
    "P_31": "p_31",
    "P_32": "p_32",
    "pref_index": "pref_index",
    "P_series": "p_series",
    "Thermal_P_var": "thermal_p_var",
    "w": "num_windows",
    "cw11": "cw11",
    "cw12": "cw12",
    "cw21": "cw21",
    "cw22": "cw22",
    "cw31": "cw31",
    "cw32": "cw32",
    "fixed": "fixed",
    "flat": "flat",
    "c": "func_cycle",
    "t": "func_time",
    "n": "number",
    "occasional_use": "occasional_use",
    "r_c1": "r_c1",
    "r_c2": "r_c2",
    "r_c3": "r_c3",
    "r_t": "time_fraction_random_variability",
    "random_var_w": "random_var_w",
    "t_11": "t_11",
    "t_12": "t_12",
    "wd_we_type": "wd_we_type",
    "window_1": "window_1",
    "window_2": "window_2",
    "window_3": "window_3",
}

NEW_TO_OLD_MAPPING = {value: key for (key, value) in OLD_TO_NEW_MAPPING.items()}


APPLIANCE_ATTRIBUTES = (
            "name",
            "number",
            "power",
            "num_windows",
            "func_time",
            "time_fraction_random_variability",
            "func_cycle",
            "fixed",
            "fixed_cycle",
            "occasional_use",
            "flat",
            "thermal_p_var",
            "pref_index",
            "wd_we_type",
            "p_11",
            "t_11",
            "cw11",
            "p_12",
            "t_12",
            "cw12",
            "r_c1",
            "p_21",
            "t_21",
            "cw21",
            "p_22",
            "t_22",
            "cw22",
            "r_c2",
            "p_31",
            "t_31",
            "cw31",
            "p_32",
            "t_32",
            "cw32",
            "r_c3",
            "window_1",
            "window_2",
            "window_3",
            "random_var_w",
        )